global:
  scrape_interval: 15s

scrape_configs:
  # Job do próprio Prometheus
  - job_name: prometheus
    honor_timestamps: true
    track_timestamps_staleness: false
    scrape_interval: 15s
    scrape_timeout: 10s
    scrape_protocols:
      - OpenMetricsText1.0.0
      - OpenMetricsText0.0.1
      - PrometheusText1.0.0
      - PrometheusText0.0.4
    always_scrape_classic_histograms: false
    convert_classic_histograms_to_nhcb: false
    metrics_path: /metrics
    scheme: http
    enable_compression: true
    metric_name_validation_scheme: utf8
    metric_name_escaping_scheme: allow-utf-8
    follow_redirects: true
    enable_http2: true
    static_configs:
      - targets:
          - localhost:9090
        labels:
          app: prometheus

  # Job do Node.js (suas métricas)
  - job_name: teste
    honor_timestamps: true
    track_timestamps_staleness: false
    scrape_interval: 15s
    scrape_timeout: 10s
    scrape_protocols:
      - OpenMetricsText1.0.0
      - OpenMetricsText0.0.1
      - PrometheusText1.0.0
      - PrometheusText0.0.4
    always_scrape_classic_histograms: false
    convert_classic_histograms_to_nhcb: false
    metrics_path: /metrics
    scheme: http
    enable_compression: true
    metric_name_validation_scheme: utf8
    metric_name_escaping_scheme: allow-utf-8
    follow_redirects: true
    enable_http2: true
    static_configs:
      - targets:
          - host.docker.internal:300   # <-- IP do host Windows acessível pelo Docker
        labels:
          app: teste

otlp:
  translation_strategy: UnderscoreEscapingWithSuffixes
